FROM ubuntu:16.10
MAINTAINER marcospedreiro

RUN apt-get update && \
      apt-get install qemu uml-utilities -y

# virt-manager
# https://hub.docker.com/r/mainto/kvm-mac/
# https://sebgoa.blogspot.com/2015/05/running-vms-in-docker-containers-via.html
# https://github.com/rancher/vm
# https://github.com/BBVA/kvm
# 
